/// Task model for the Tasks module.
///
/// Maps to Supabase `tasks` table.
class Task {
  final String id;
  final String userId;
  final String title;
  final String? description;
  final DateTime? dueDate;
  final String priority; // 'low', 'medium', 'high'
  final bool completed;
  final bool reminder;
  final DateTime createdAt;

  const Task({
    required this.id,
    required this.userId,
    required this.title,
    this.description,
    this.dueDate,
    this.priority = 'medium',
    this.completed = false,
    this.reminder = false,
    required this.createdAt,
  });

  /// Whether this task is overdue.
  bool get isOverdue {
    if (dueDate == null || completed) return false;
    return dueDate!.isBefore(DateTime.now());
  }

  Task copyWith({
    String? id,
    String? userId,
    String? title,
    String? description,
    DateTime? dueDate,
    String? priority,
    bool? completed,
    bool? reminder,
    DateTime? createdAt,
  }) {
    return Task(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      title: title ?? this.title,
      description: description ?? this.description,
      dueDate: dueDate ?? this.dueDate,
      priority: priority ?? this.priority,
      completed: completed ?? this.completed,
      reminder: reminder ?? this.reminder,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  factory Task.fromJson(Map<String, dynamic> json) {
    return Task(
      id: json['id']?.toString() ?? '',
      userId: json['user_id'] as String? ?? '',
      title: json['title'] as String? ?? 'Untitled',
      description: json['description'] as String?,
      dueDate: json['due_date'] != null
          ? DateTime.tryParse(json['due_date'].toString())
          : null,
      priority: json['priority'] as String? ?? 'medium',
      completed: json['is_completed'] as bool? ?? json['completed'] as bool? ?? false,
      reminder: json['reminder'] as bool? ?? false,
      createdAt: DateTime.tryParse(json['created_at']?.toString() ?? '') ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{
      'user_id': userId,
      'title': title,
      'priority': priority,
      'is_completed': completed,
      'reminder': reminder,
    };
    if (description != null) map['description'] = description;
    if (dueDate != null) map['due_date'] = dueDate!.toIso8601String();
    // Don't send id or created_at — auto-generated by Supabase
    return map;
  }

  @override
  String toString() => 'Task($title, priority=$priority, completed=$completed)';
}