/// Transaction model for Khaata.
///
/// Maps to Supabase `transactions` table.
/// `type` is 'income' or 'expense' (migrated from old credit/debit).
class Transaction {
  final String id;
  final String userId;
  final double amount;
  final String type; // 'income' or 'expense'
  final String category;
  final String? description;
  final String? person; // backward compat
  final DateTime timestamp;

  const Transaction({
    required this.id,
    required this.userId,
    required this.amount,
    required this.type,
    required this.category,
    this.description,
    this.person,
    required this.timestamp,
  });

  /// Whether this is an income entry.
  bool get isIncome => type == 'income';

  /// Format amount with ₹ sign.
  String get formattedAmount => '₹${amount.toStringAsFixed(amount.truncateToDouble() == amount ? 0 : 2)}';

  /// Display label — prefers description, falls back to person, then category.
  String get displayLabel => description ?? person ?? category;

  Transaction copyWith({
    String? id,
    String? userId,
    double? amount,
    String? type,
    String? category,
    String? description,
    String? person,
    DateTime? timestamp,
  }) {
    return Transaction(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      amount: amount ?? this.amount,
      type: type ?? this.type,
      category: category ?? this.category,
      description: description ?? this.description,
      person: person ?? this.person,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  factory Transaction.fromJson(Map<String, dynamic> json) {
    // Handle legacy credit/debit → income/expense mapping
    String resolvedType = json['type'] as String? ?? 'expense';
    final category = json['category'] as String? ?? 'Other';
    if (resolvedType.isEmpty || (resolvedType != 'income' && resolvedType != 'expense')) {
      if (category == 'credit') {
        resolvedType = 'income';
      } else {
        resolvedType = 'expense';
      }
    }

    return Transaction(
      id: json['id']?.toString() ?? '',
      userId: json['user_id'] as String? ?? '',
      amount: (json['amount'] as num?)?.toDouble() ?? 0.0,
      type: resolvedType,
      category: category,
      description: json['description'] as String?,
      person: json['person'] as String?,
      timestamp: DateTime.tryParse(json['created_at']?.toString() ?? '') ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{
      'user_id': userId,
      'amount': amount,
      'type': type,
      'category': category,
    };
    if (description != null) map['description'] = description;
    if (person != null) map['person'] = person;
    // Don't send id or created_at — auto-generated by Supabase
    return map;
  }

  @override
  String toString() => 'Transaction($type: ₹$amount $category - $displayLabel)';
}